services:
  laravel:
    container_name: laravel
    image: bitnami/laravel:latest
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bitnami_myapp
      - DB_USERNAME=bn_myapp
    depends_on:
      - mariadb
    volumes:
      - ./dajare-SNS:/app
    networks:
      - laravel-net

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    depends_on:
      - mariadb
    networks:
      - laravel-net

  mariadb:
    container_name: mariadb
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=bitnami_myapp
      - MARIADB_USER=bn_myapp
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - laravel-net

volumes:
  mariadb_data:
    driver: local
    name: mariadb_data

networks:
  laravel-net:
    name: laravel-net
    driver: bridge
